name: booking_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  retrofit: '>=3.0.0 <4.0.0'
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  bloc: ^8.1.0
  http: ^0.13.5
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  get_it: ^7.2.0
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5
  dartz: ^0.10.1
  smooth_page_indicator: ^1.0.0+2
  marquee: ^2.2.3
  font_awesome_flutter: ^10.2.1
  conditional_builder_null_safety: ^0.0.6
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^4.1.1
  google_maps_flutter: ^2.2.0
  dio: ^4.0.6
  fluttertoast: ^8.0.9
  image_picker: ^0.7.4
  location: ^4.4.0
  lottie: ^1.4.3

dev_dependencies:
  build_runner: ^2.2.1
  retrofit_generator: '>=4.0.0 <5.0.0'

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/boarding/
    - assets/user/
    - assets/lotties/


  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Light.ttf
